Given a number n, find the smallest number that has same set of digits as n and is greater than n.  If x is the greatest possible number with its set of digits, then print “not possible”.Examples:
For simplicity of implementation, we have considered input number as a string.  We strongly recommend to minimize the browser and try this yourself first.Following are few observations about the next greater number.
1) If all digits sorted in descending order, then output is always “Not Possible”.  For example, 4321.
2) If all digits are sorted in ascending order, then we need to swap last two digits.  For example, 1234.
3) For other cases, we need to process the number from rightmost side (why? because we need to find the smallest of all greater numbers)You can now try developing an algorithm yourself.  Following is the algorithm for finding the next greater number.
I) Traverse the given number from rightmost digit, keep traversing till you find a digit which is smaller than the previously traversed digit.  For example, if the input number is “534976”, we stop at 4 because 4 is smaller than next digit 9.  If we do not find such a digit, then output is “Not Possible”.II) Now search the right side of above found digit ‘d’ for the smallest digit greater than ‘d’.  For “534976″, the right side of 4 contains “976”.  The smallest digit greater than 4 is 6.III) Swap the above found two digits, we get 536974 in above example.IV) Now sort all digits from position next to ‘d’ to the end of number. The number that we get after sorting is the output.  For above example, we sort digits in bold 536974.  We get “536479” which is the next greater number for input 534976.Following is C++ implementation of above approach.Output:
Next number with same set of digits is 536479
The above implementation can be optimized in following ways.
1) We can use binary search in step II instead of linear search.
2) In step IV, instead of doing simple sort, we can apply some clever technique to do it in linear time.  Hint: We know that all digits are linearly sorted in reverse order except one digit which was swapped.With above optimizations, we can say that the time complexity of this method is O(n). This article is contributed by Rahul Jain.  Please write comments if you find anything incorrect, or you want to share more information about the topic discussed aboveTags: MathematicalAlgo