Given a graph which represents a flow network where every edge has a capacity. Also given two vertices source  ‘s’ and sink ‘t’ in the graph, find the maximum possible flow from s to t with following constraints:a) Flow on an edge doesn’t exceed the given capacity of the edge.b) Incoming flow is equal to outgoing flow for every vertex except s and t.For example, consider the following graph from CLRS book.
The maximum possible flow in the above graph is 23.
Time Complexity: Time complexity of the above algorithm is O(max_flow * E). We run a loop while there is an augmenting path. In worst case, we may add 1 unit flow in every iteration. Therefore the time complexity becomes O(max_flow * E). How to implement the above simple algorithm?  
Let us first define the concept of Residual Graph which is needed for understanding the implementation.
Residual Graph of a flow network is a graph which indicates additional possible flow. If there is a path from source to sink in residual graph, then it is possible to add flow.   Every edge of a residual graph has a value called residual capacity which is equal to original capacity of the edge minus current flow. Residual capacity is basically the current capacity of the edge.
Let us now talk about implementation details. Residual capacity is 0 if there is no edge between to vertices of residual graph. We can initialize the residual graph as original graph as there is no initial flow and initially residual capacity is equal to original capacity.  To find an augmenting path, we can either do a BFS or DFS of the residual graph.  We have used BFS in below implementation. Using BFS, we can find out if there is a path from source to sink. BFS also builds parent[] array. Using the parent[] array, we traverse through the found path and find possible flow through this path by finding minimum residual capacity along the path. We later add the found path flow to overall flow.
The important thing is, we need to update residual capacities in the residual graph.  We subtract path flow from all edges along the path and we add path flow along the reverse edges We need to add path flow along reverse edges because may later need to send flow in reverse direction (See following video for example).http://www.youtube.com/watch?v=-8MwfgB-lyMFollowing is C++ implementation of Ford-Fulkerson algorithm.  To keep things simple, graph is represented as a 2D matrix. Output:
The maximum possible flow is 23
The above implementation of Ford Fulkerson Algorithm is called Edmonds-Karp Algorithm.  The idea of Edmonds-Karp is to use BFS in Ford Fulkerson implementation as BFS always picks a path with minimum number of edges.  When BFS is used, the worst case time complexity can be reduced to O(VE2). The above implementation uses adjacency matrix representation though where BFS takes O(V2) time, the time complexity of the above implementation is O(EV3) (Refer CLRS book for proof of time complexity)This is an important problem as it arises in many practical situations.  Examples include, maximizing the transportation with given traffic limits, maximizing packet flow in computer networks. Exercise:
Modify the above implementation so that it that runs in O(VE2) time.References:
http://www.stanford.edu/class/cs97si/08-network-flow-problems.pdf
Introduction to Algorithms 3rd Edition by Clifford Stein, Thomas H. Cormen, Charles E. Leiserson, Ronald L. RivestPlease write comments if you find anything incorrect, or you want to share more information about the topic discussed above.Tags: Graph