Eulerian Path is a path in graph that visits every edge exactly once. Eulerian Circuit is an Eulerian Path which starts and ends on the same vertex.We strongly recommend to first read the following post on Euler Path and Circuit.
http://www.geeksforgeeks.org/eulerian-path-and-circuit/In the above mentioned post, we discussed the problem of finding out whether a given graph is Eulerian or not. In this post, an algorithm to print Eulerian trail or circuit is discussed.Following is Fleury’s Algorithm for printing Eulerian trail or cycle (Source Ref1).1. Make sure the graph has either 0 or 2 odd vertices.2. If there are 0 odd vertices, start anywhere. If there are 2 odd vertices, start at one of them.3. Follow edges one at a time. If you have a choice between a bridge and a non-bridge, always choose the non-bridge.4. Stop when you run out of edges.The idea is, “don’t burn bridges“ so that we can come back to a vertex and traverse remaining edges.  For example let us consider the following graph. There are two vertices with odd degree, ‘2’ and ‘3’, we can start path from any of them. Let us start tour from vertex ‘2’.

There are three edges going out from vertex ‘2’, which one to pick? We don’t pick the edge ‘2-3′ because that is a bridge (we won’t be able to come back to ‘3’).  We can pick any of the remaining two edge. Let us say we pick ‘2-0′. We remove this edge and move to vertex ‘0’.

There is only one edge from vertex ‘0’, so we pick it, remove it and move to vertex ‘1’. Euler tour becomes ‘2-0 0-1′.
There is only one edge from vertex ‘1’, so we pick it, remove it and move to vertex ‘2’. Euler tour becomes ‘2-0 0-1 1-2′
Again there is only one edge from vertex 2, so we pick it, remove it and move to vertex 3. Euler tour becomes ‘2-0 0-1 1-2 2-3′
There are no more edges left, so we stop here.  Final tour is ‘2-0 0-1 1-2 2-3′.See this for and this fore more examples.Following is C++ implementation of above algorithm.  In the following code, it is assumed that the given graph has an Eulerian trail or Circuit. The main focus is to print an Eulerian trail or circuit. We can use isEulerian() to first check whether there is an Eulerian Trail or Circuit in the given graph. We first find the starting point which must be an odd vertex (if there are odd vertices) and store it in variable ‘u’. If there are zero odd vertices, we start from vertex ‘0’. We call printEulerUtil() to print Euler tour starting with u. We traverse all adjacent vertices of u, if there is only one adjacent vertex, we immediately consider it. If there are more than one adjacent vertices, we consider an adjacent v only if edge u-v is not a bridge. How to find if a given is edge is bridge? We count number of vertices reachable from u. We remove edge u-v and again count number of reachable vertices from u. If number of reachable vertices are reduced, then edge u-v is a bridge. To count reachable vertices, we can either use BFS or DFS, we have used DFS in the above code. The function DFSCount(u) returns number of vertices reachable from u.
Once an edge is processed (included in Euler tour), we remove it from the graph.  To remove the edge, we replace the vertex entry with -1 in adjacency list.  Note that simply deleting the node may not work as the code is recursive and a parent call may be in middle of adjacency list.Output:
2-0  0-1  1-2  2-3
0-1  1-2  2-0
0-1  1-2  2-0  0-3  3-4  4-2  2-3  3-1
Note that the above code modifies given graph, we can create a copy of graph if we don’t want the given graph to be modified.Time Complexity: Time complexity of the above implementation is O ((V+E)2).  The function printEulerUtil() is like DFS and it calls isValidNextEdge() which also does DFS two times.  Time complexity of DFS for adjacency list representation is O(V+E). Therefore overall time complexity is O((V+E)*(V+E)) which can be written as O(E2) for a connected graph. There are better algorithms to print Euler tour, we will soon be covering them as separate posts.References:
http://www.math.ku.edu/~jmartin/courses/math105-F11/Lectures/chapter5-part2.pdf
http://en.wikipedia.org/wiki/Eulerian_path#Fleury.27s_algorithmPlease write comments if you find anything incorrect, or you want to share more information about the topic discussed aboveTags: Graph